version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: subscription-challenge-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: subscription-challenge
    volumes:
      - mongodb_data:/data/db
    networks:
      - subscription-network

  redis:
    image: redis:7.2-alpine
    container_name: subscription-challenge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - subscription-network

volumes:
  mongodb_data:

networks:
  subscription-network:
    driver: bridge
